# Numpy learning

In [1]:
import numpy as np

In [2]:
myarr = np.array([5,10,15,20,25],np.int8)

int8 means data should be 8 bit

In [3]:
myarr

array([ 5, 10, 15, 20, 25], dtype=int8)

In [4]:
myarr[1]

10

In [5]:
arr2 = np.array([[12,56,34]])

In [6]:
arr2[0,2]

34

In [7]:
arr2[0]

array([12, 56, 34])

In [8]:
arr2.shape

(1, 3)

In [9]:
myarr.dtype

dtype('int8')

In [10]:
arr2.dtype

dtype('int32')

In [11]:
arr2

array([[12, 56, 34]])

In [12]:
arr2[0,2] = 78

In [13]:
arr2

array([[12, 56, 78]])

# Array Creation

**Converting Python sequences to NumPy Arrays**

In [14]:
listarr = np.array([[2,4,6],[3,9,12],[4,8,12]])

In [15]:
listarr

array([[ 2,  4,  6],
       [ 3,  9, 12],
       [ 4,  8, 12]])

In [16]:
listarr.size

9

In [17]:
np.array({1,9,4})

array({1, 4, 9}, dtype=object)

In [18]:
zarr = np.zeros((3,4))

In [19]:
zarr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
zarr.dtype

dtype('float64')

In [21]:
zarr.shape

(3, 4)

In [22]:
rarr = np.arange(20)

In [23]:
rarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
larr = np.linspace(1,5,9)

In [27]:
larr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [28]:
larr2 = np.linspace(1,5,10)

In [29]:
larr2

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [36]:
larr3 = np.linspace(1,60,10)

In [37]:
larr3

array([ 1.        ,  7.55555556, 14.11111111, 20.66666667, 27.22222222,
       33.77777778, 40.33333333, 46.88888889, 53.44444444, 60.        ])

In [39]:
earr = np.empty((4,6))

In [40]:
earr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        1.33512376e-306, 6.89806849e-307, 9.34609790e-307],
       [1.69121096e-306, 1.05700515e-307, 1.11261774e-306,
        1.29060871e-306, 8.34424766e-308, 2.12203497e-312]])

In [41]:
iarr = np.identity(9)

In [42]:
iarr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
iarr.shape

(9, 9)

In [44]:
newarr = np.arange(88)

In [45]:
newarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [47]:
newarr = newarr.reshape(4,22)

In [48]:
newarr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
        60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87]])

In [49]:
newarr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87])

In [52]:
xlist = [[1,2,3],[4,5,6],[7,8,9]]

In [53]:
xarr = np.array(xlist)

In [54]:
xarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
xarr.sum(axis=0)

array([12, 15, 18])

In [57]:
xarr.sum(axis=1)

array([ 6, 15, 24])

In [58]:
xarr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [59]:
xarr.flat

In [61]:
for i in xarr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [62]:
xarr_transpose = xarr.T

In [63]:
xarr_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
for i in xarr_transpose.flat:
    print(i)

1
4
7
2
5
8
3
6
9


In [65]:
xarr.ndim

2

In [67]:
xarr.size

9

In [68]:
xarr.nbytes

36

In [76]:
oarray = np.array([5,10,7,2,15,12])

In [79]:
oarray.argmax() #max index

4

In [80]:
oarray.argmin() #min index

3

In [81]:
oarray.argsort() #sorting of index

array([3, 0, 2, 1, 5, 4], dtype=int64)

In [102]:
ylist = [[5,10,25],[5,1,2],[7,11,0]]

In [103]:
yarr = np.array(ylist)

In [104]:
yarr

array([[ 5, 10, 25],
       [ 5,  1,  2],
       [ 7, 11,  0]])

In [105]:
yarr.argmax()

2

In [106]:
yarr.argmin()

8

In [107]:
yarr.argmax(axis=0)

array([2, 2, 0], dtype=int64)

In [108]:
yarr.argmax(axis=1)

array([2, 0, 1], dtype=int64)

In [109]:
yarr.argsort(axis=0)

array([[0, 1, 2],
       [1, 0, 1],
       [2, 2, 0]], dtype=int64)

In [110]:
yarr.argsort(axis=1)

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]], dtype=int64)

In [111]:
yarr.ravel()

array([ 5, 10, 25,  5,  1,  2,  7, 11,  0])

In [112]:
yarr.reshape(9,1)

array([[ 5],
       [10],
       [25],
       [ 5],
       [ 1],
       [ 2],
       [ 7],
       [11],
       [ 0]])

In [113]:
xarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
yarr

array([[ 5, 10, 25],
       [ 5,  1,  2],
       [ 7, 11,  0]])

In [115]:
xarr + yarr

array([[ 6, 12, 28],
       [ 9,  6,  8],
       [14, 19,  9]])

In [116]:
xarr * yarr

array([[ 5, 20, 75],
       [20,  5, 12],
       [49, 88,  0]])

In [117]:
np.sqrt(xarr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [118]:
yarr

array([[ 5, 10, 25],
       [ 5,  1,  2],
       [ 7, 11,  0]])

In [119]:
yarr.sum()

66

In [120]:
yarr.max()

25

In [121]:
yarr.min()

0

In [122]:
np.where(yarr>9)

(array([0, 0, 2], dtype=int64), array([1, 2, 1], dtype=int64))

In [124]:
xarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
np.where(xarr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [128]:
type(np.where(xarr>5))

tuple

In [129]:
yarr

array([[ 5, 10, 25],
       [ 5,  1,  2],
       [ 7, 11,  0]])

In [130]:
np.count_nonzero(yarr)

8

In [131]:
np.nonzero(yarr)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [136]:
yarr[1,1] = 0

In [137]:
np.nonzero(yarr)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [138]:
yarr[1,1] = 9

In [139]:
import sys

In [140]:
pyarray = [4,12,20,16]

In [141]:
nparray = np.array(pyarray)

In [142]:
sys.getsizeof(1) * len(pyarray)

112

In [143]:
nparray.itemsize * nparray.size

16

In [144]:
nparray.tolist()

[4, 12, 20, 16]

In [145]:
nparray

array([ 4, 12, 20, 16])